In [2]:
import numpy as np
import pandas as pd

In [16]:
retail=pd.read_csv(r'C:\Users\Asus\Desktop\DA_PROJECT\dataset\online_retail_raw.csv')
retail.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom

In [19]:
retail.tail(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [ ]:
retail.columns=retail.columns.str.lower()
retail.columns=retail.columns.str.replace(' ','_')

In [65]:
retail.columns

Index(['invoice', 'stockcode', 'description', 'quantity', 'invoicedate',
       'price', 'customer_id', 'country'],
      dtype='str')

In [29]:
retail.shape

(1067371, 8)

In [32]:
retail.isnull().sum()

invoice             0
stockcode           0
description      4382
quantity            0
invoicedate         0
price               0
customer_id    243007
country             0
dtype: int64

In [39]:
retail.isnull().sum()

invoice             0
stockcode           0
description      4382
quantity            0
invoicedate         0
price               0
customer_id    243007
country             0
dtype: int64

In [54]:
retail.duplicated().sum()

np.int64(34335)

- from the above queries we have concluded that we have some missing values and also duplicated rows.
Lets fix them.

In [56]:
retail.drop_duplicates(inplace=True)

In [57]:
retail.duplicated().sum()

np.int64(0)

In [59]:
# we have 4382 missing description in rows. As we are dealing with around 10L rows over two years it is safe to drop them.
retail['description'][retail['description']==None]

Series([], Name: description, dtype: str)

In [60]:
retail.dropna(subset=['description'],inplace=True)

In [62]:
# now we have around 243k rows with missing customer_id ,let's assume these were purchases without customer account . Lets call them Guest and fill these rows with customer_id=0
retail['customer_id']=retail['customer_id'].fillna(0)

In [64]:
retail.isnull().sum()

invoice        0
stockcode      0
description    0
quantity       0
invoicedate    0
price          0
customer_id    0
country        0
dtype: int64

In [68]:
retail[retail['invoice'].astype(str).str.startswith('C')]

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
1067002,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [69]:
retail['is_cancelled']=retail['invoice'].astype(str).str.startswith('C').astype(int)

In [110]:
retail[(retail['quantity']>0) & retail['is_cancelled']==1]

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,is_cancelled,year,month
76799,C496350,M,Manual,1,2010-02-01 08:24:00,373.57,0.0,United Kingdom,1,2010,2

In [94]:
retail[retail['quantity']<0]

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,is_cancelled,year,month
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia,1,2009,12
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia,1,2009,12
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia,1,2009,12
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia,1,2009,12
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia,1,2009,12
...,...,...,...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom,1,2011,12
1067002,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom,1,2011,12
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom,1,2011,12
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom,1,2011,12
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom,1,2011,12

In [91]:
retail[(retail['quantity']>0) & retail['is_cancelled']==1]

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,is_cancelled,year,month
76799,C496350,M,Manual,1,2010-02-01 08:24:00,373.57,0.0,United Kingdom,1,2010,2

In [92]:
retail[retail['description']=='Manual']

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,is_cancelled,year,month
2697,489609,M,Manual,1,2009-12-01 14:50:00,4.00,0.0,United Kingdom,0,2009,12
3053,C489651,M,Manual,-1,2009-12-01 16:48:00,5.10,17804.0,United Kingdom,1,2009,12
5897,C489859,M,Manual,-1,2009-12-02 14:45:00,69.57,0.0,United Kingdom,1,2009,12
9259,C490126,M,Manual,-1,2009-12-03 18:12:00,5.95,15884.0,United Kingdom,1,2009,12
9307,C490129,M,Manual,-1,2009-12-03 18:26:00,1998.49,15482.0,United Kingdom,1,2009,12
...,...,...,...,...,...,...,...,...,...,...,...
1056893,580956,M,Manual,4,2011-12-06 14:23:00,1.25,17841.0,United Kingdom,0,2011,12
1058543,C581009,M,Manual,-1,2011-12-07 09:15:00,125.00,16971.0,United Kingdom,1,2011,12
1059769,C581145,M,Manual,-1,2011-12-07 13:48:00,9.95,17490.0,United Kingdom,1,2011,12
1063782,581405,M,Manual,3,2011-12-08 13:50:00,0.42,13521.0,United Kingdom,0,2011,12
1067002,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom,1,2011,12

In [129]:
retail['invoicedate'] = pd.to_datetime(retail['invoicedate'])
retail['year']=retail['invoicedate'].dt.year
retail['month']=retail['invoicedate'].dt.month

In [82]:
retail['month'].unique()

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [80]:
retail['year'].unique()

array([2009, 2010, 2011], dtype=int32)

In [111]:
retail['total_revenue']=retail['quantity'] *  retail['price']

In [112]:
retail

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,is_cancelled,year,month,total_revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,0,2009,12,83.40
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,0,2009,12,81.00
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,0,2009,12,81.00
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,0,2009,12,100.80
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,0,2009,12,30.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,0,2011,12,12.60
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,0,2011,12,16.60
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,0,2011,12,16.60
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,0,2011,12,14.85
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France,0,2011,12,18.00

In [119]:
#total revenue also contains when the quantity is negative 
#only positive
gross_revenue=retail[retail['quantity']>0]['total_revenue'].sum()
print(gross_revenue)
#negative also included
net_revenue=retail['total_revenue'].sum()
print(net_revenue)

gap=gross_revenue-net_revenue
print(gap)

20317957.878000002
18855533.698
1462424.1800000034

In [120]:
retail.to_csv('online_retail_analysed.csv',index=False)

In [125]:
retail.shape

(1028761, 12)

In [126]:
retail['description'].unique()

<StringArray>
['15CM CHRISTMAS GLASS BALL 20 LIGHTS',                  'PINK CHERRY LIGHTS',
                ' WHITE CHERRY LIGHTS',        'RECORD FRAME 7" SINGLE SIZE ',
      'STRAWBERRY CERAMIC TRINKET BOX',          'PINK DOUGHNUT TRINKET POT ',
                 'SAVE THE PLANET MUG',  'FANCY FONT HOME SWEET HOME DOORMAT',
                           'CAT BOWL ',      'DOG BOWL , CHASING BALL DESIGN',
 ...
      'SET 10 CARDS SNOWY ROBIN 17099', 'SET 10 CARDS SWIRLY XMAS TREE 17104',
                                'wet?',                              'lost??',
                                 '???',                           'wet boxes',
                     '????damages????',                            'mixed up',
  'CREAM HANGING HEART T-LIGHT HOLDER',         'PAPER CRAFT , LITTLE BIRDIE']
Length: 5698, dtype: str

In [127]:
retail['description'].nunique()

5698

In [122]:
%pip install mysql-connector-python sqlalchemy

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.3.2-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   -- ------------------------------------- 1.0/16.5 MB 9.8 MB/s eta 0:00:02
   --- ------------------------------------ 1.3/16.5 MB 3.5 MB/s eta 0:00:05
   ------- -------------------------------- 3.1/16.5 MB 6.6 MB/s eta 0:00:03
   -------- ------------------------------- 3.7/16.5 MB 4.7 MB/s eta 0:00:03
   ------------ --------------------------- 5.2/16.5 MB 6.1 MB/s eta 0:00:02
   --------------- ------------------------ 6.6/16.5 MB 5.4 MB/s eta 0:00:02
   ----------------- ---------------------- 7.3/16.5 MB 5.9 MB/s eta 0:00:02
   ----------------- ---------------------- 7.3/16.5 MB 5.9 MB/s eta 0:00:02
   -------------------- ------------------- 8.4/16.5 MB 5.0 MB/s eta 0:00:02
   -------------------- ------------------- 8.4/16.5 MB 5.0 MB/s eta 0:00:02
   -------------------- ------------------- 8.4/16.5 MB 5.0 MB/s eta 0:00:02
   ---------------------- ----------------- 9.4/16.5 MB 3.8 MB/s eta 0:00:02
   ----------------------------------- ---- 14.7/16.5 MB 5.5 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 5.8 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 5.8 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 4.8 MB/s eta 0:00:00
Using cached sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl (2.1 MB)
Using cached greenlet-3.3.2-cp313-cp313-win_amd64.whl (230 kB)
Installing collected packages: mysql-connector-python, greenlet, sqlalchemy
Successfully installed greenlet-3.3.2 mysql-connector-python-9.6.0 sqlalchemy-2.0.48
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [124]:
from sqlalchemy import create_engine

user = 'root'
password = 'password' 
host = 'localhost'
port = '3306'
database = 'retail_db'

engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")

engine.dispose() 

try:
    file_path = r'C:\Users\Asus\Desktop\DA_PROJECT\online_retail_analysed.csv'
    df_to_upload = pd.read_csv(file_path)

    print(f"Starting upload of {len(df_to_upload)} rows to MySQL...")

    df_to_upload.to_sql(
        name='sales_data', 
        con=engine, 
        if_exists='replace', 
        index=False, 
        chunksize=20000
    )
    
    print(" Upload complete! Table 'sales_data' is ready in MySQL.")

except Exception as e:
    print(f"Error occurred: {e}")

Starting upload of 1028761 rows to MySQL...
 Upload complete! Table 'sales_data' is ready in MySQL.

In [ ]:
retail['month'][retail['year']==2009].nunique()
# so for 2009 only december data is there

1